zadaca5/urls.py
from django.contrib import admin
from django.urls import path
from CaseStoreApp.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', cases, name="cases"),
    path('cases/', cases, name="cases"),
    path('case_details/<int:case_id>/', case_details, name="case_details"),
    path('cart_items/', cart_items, name="cart_items"),
    path('checkout/', checkout, name="checkout"),
    path('final_site/', final_site, name="final_site"),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('item/delete/<int:item_id>/', delete_item, name='delete_item'),
    path('item/add/', add_item, name='add_item'),
    path('edit_item/<int:item_id>/', edit_item, name='edit_item'),
    path('cart/item/delete/<int:item_id>/', delete_cart_item, name='delete_cart_item'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CaseStoreApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User


class Product(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    phone_type = models.CharField(max_length=100)
    material = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    image = models.ImageField(upload_to="case_images/")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart for {self.user.username}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.product} ({self.quantity}) in Cart"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    counrty = models.CharField(max_length=50)
    city_postal = models.CharField(max_length=50)
    shipping_address = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)
    pay_with_card = models.BooleanField(default=True)

    def __str__(self):
        return f"Order #{self.pk} by {self.user}"

    def calculate_total_amount(self):
        total = 0
        cart_items = self.cart.items.all()
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
        return total

CaseStoreApp/forms.py
from django import forms
from .models import *


class ItemForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'color', 'phone_type', 'material', 'description', 'price', 'quantity', 'image']


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['counrty', 'city_postal', 'shipping_address', 'phone_number', 'pay_with_card']
        labels = {
            'counrty': 'Country',
            'city_postal': 'City / Postal',
            'shipping_address': 'Shipping Address',
            'phone_number': 'Phone Number',
            'pay_with_card': 'Pay with Card',
        }
        widgets = {
            'pay_with_card': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

CaseStoreApp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from .forms import CheckoutForm, ItemForm


def cases(request):
    query = request.GET.get('search_query', '')
    phone_type = request.GET.getlist('phone_type')
    material = request.GET.getlist('material')
    color = request.GET.getlist('color')
    all_cases = Product.objects.all()

    if query:
        all_cases = all_cases.filter(phone_type__icontains=query)

    if phone_type:
        all_cases = all_cases.filter(phone_type__in=phone_type)

    if material:
        all_cases = all_cases.filter(material__in=material)

    if color:
        all_cases = all_cases.filter(color__in=color)

    return render(request, 'cases.html',
                  {'cases': all_cases, 'query': query, 'selected_phone_type': phone_type, 'selected_material': material,
                   'selected_color': color, 'user': request.user})


@login_required(login_url='login')
def case_details(request, case_id):
    case = get_object_or_404(Product, id=case_id)
    cart, created = Cart.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 1))
        # Check if the purchased quantity is available
        if quantity <= case.quantity:
            cart_item, created = CartItem.objects.get_or_create(cart=cart, product=case)
            cart_item.quantity = quantity
            cart_item.save()
            return redirect('cart_items')
        else:
            return HttpResponse("Insufficient quantity available")
    return render(request, 'case_details.html', {'case': case})


@login_required
def delete_item(request, item_id):
    item = get_object_or_404(Product, id=item_id)
    item.delete()
    return redirect('cases')


@login_required
def edit_item(request, item_id):
    item = get_object_or_404(Product, id=item_id)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('case_details', case_id=item.id)
    else:
        form = ItemForm(instance=item)
    return render(request, 'edit_product.html', {'form': form, 'item': item})


@login_required
def add_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('case_details', case_id=form.save().id)  # Redirect to the cart or any other appropriate URL
    else:
        form = ItemForm()
    return render(request, 'add_product.html', {'form': form})


@login_required(login_url='login')
def cart_items(request):
    items = CartItem.objects.filter(cart__user=request.user)
    cart_total = sum(item.product.price * item.quantity for item in items)
    context = {'cart_items': items, 'total': cart_total}
    return render(request, 'cart_items.html', context)


@login_required
def delete_cart_item(request, item_id):
    item = get_object_or_404(CartItem, id=item_id)
    item.delete()
    return redirect('cart_items')


@login_required(login_url='login')
def checkout(request):
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.cart = request.user.cart  # Assuming you have associated each user with a cart
            order.total_amount = order.calculate_total_amount()  # Calculate the total amount
            order.save()
            # Subtract the purchased quantities from the products' quantities
            items = order.cart.items.all()
            for cart_item in items:
                cart_item.product.quantity -= cart_item.quantity
                cart_item.product.save()
            # Clear the cart items
            request.user.cart.items.all().delete()
            # Redirect or render success page
            return redirect('final_site')
        # else:
        #     return redirect('cases')
    else:
        form = CheckoutForm()
    context = {'form': form}
    return render(request, 'checkout.html', context)


@login_required(login_url='login')
def final_site(request):
    return render(request, 'final_site.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('cases')
        else:
            # Handle invalid login credentials
            return render(request, 'login.html', {'error': 'Invalid login credentials.'})
    return render(request, 'login.html')

CaseStoreApp/templates/add_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SupCase</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
<style>
      body {
            background-color: #f1f1f1;
        }
</style>
</head>
<body class="container">
{% include 'header.html' %}<hr>
<h3 class="mt-4">Add New Item:</h3>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
    <button type="submit" class="btn btn-primary mb-5">Add Item</button>
</form>
</body>
</html>

CaseStoreApp/templates/cart_items.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SupCase</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <style>
        .btn-danger:hover{
            background-color: black !important;
        }
         body {
            background-color: #f1f1f1;
        }
    </style>
</head>
<body class="container">
{% include 'header.html' %}<hr>
{% block content %}
  <h3 class="mt-5">Cart Items: </h3>
  {% if cart_items %}
    <table class="table">
  <thead>
    <tr>
        <th scope="col">Picture</th>
      <th class="text-center" scope="col">Name</th>
      <th class="text-center" scope="col">Quantity</th>
      <th class="text-center" scope="col">Price</th>
        <th></th>
    </tr>
  </thead>
  <tbody>
     {% for item in cart_items %}
         <tr>
             <th scope="row"><img src="{{ MEDIA_URL }}{{ item.product.image.url }}" class="" style="height: 150px; width: 70px; "></th>
             <td class="fs-5 text-center">{{ item.product.name }}</td>
             <td class="fs-5 text-center">{{ item.quantity }}</td>
             <td class="fs-5 text-center">{{ item.product.price|multiply:item.quantity }} $</td>
             <td>
                 <form action="{% url 'delete_cart_item' item.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                  </form>
                </td>
         </tr>
      {% endfor %}
    <tr>
  </tbody>
</table>
  {% else %}
    <p>Your cart is empty.</p>
  {% endif %}
{% endblock %}
<h2 class="d-inline">Total Price:</h2>
<h2 class="d-inline">{{ total }} $</h2>

<a href="{% url 'checkout' %}" class="d-flex text-decoration-none mt-3">
    <button id="button" class="btn btn-danger rounded-pill px-4 py-2 fw-bold fs-4 text-white">Continue to checkout</button>
</a>
</body>
</html>

CaseStoreApp/templates/case_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>SupCase</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
    <style>
        a:hover{
            color: honeydew;
        }
        body {
            background-color: #f1f1f1;
        }
    </style>
</head>
<body>
<div class="container">
{% include 'header.html' %}
    <div class="row mt-5">
        <div class="col">
            <img class="" src="{{ MEDIA_URL }}{{ case.image.url }}" style="height: 550px; width: 300px;">
        </div>
        <div class="col ">
            <h3>Case Name:</h3>
            <h5 class="mb-3">{{ case.name }}</h5>
            <h3>Phone Model:</h3>
            <h5>{{ case.phone_type }}</h5>
            <h3 class="mt-3">Case Features:</h3>
            <h5>{{ case.description }}</h5>


            <form method="post" action="{% url 'case_details' case.id %}">
                {% csrf_token %}
                <h3 class="mt-3" >Quantity:</h3>
                <input type="number" name="quantity" id="quantity" value="1" min="1" onchange="updatePrice()">
                <input type="hidden" id="initialPrice" name="initialPrice" value="{{ case.price }}">
                <h3 class="mt-4">Price: <span id="totalPrice">{{ case.price }}</span> $</h3>
                <button type="submit" class="btn rounded-pill px-5 py-2 fw-bold fs-4 mt-4 text-white" style="background-color: indianred">Add to card</button>
            </form>
        </div>
    </div>

</div>
</body>
<script>
    function updatePrice() {
        var quantity = parseInt(document.getElementById('quantity').value);
        var initialPrice = parseFloat(document.getElementById('initialPrice').value);
        var totalPrice = quantity * initialPrice;
        document.getElementById('totalPrice').textContent = totalPrice.toFixed(2);
    }
</script>

</html>

CaseStoreApp/templates/cases.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>SupCase</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
    <style>
        img:hover{
            cursor: pointer;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.6);
        }
        body {
            background-color: #f1f1f1;
        }
    </style>
</head>
<body>
<div class="container">
{% include 'header.html' %}
    <div class="row mt-3">
        <div class="col-3">
            <h5 class="d-inline me-3" style="color: #444F5A">Logged in as: {{ user.username }}</h5>
        </div>
        <form method="GET" action="{% url 'cases'%}" class="col-9 d-flex">
        <input type="text" name="search_query" placeholder="Enter phone model" class=" form-control">
        <button class="btn btn-success" type="submit">Search</button>
    </form>
    </div>

    <div class="row">
        <div class="col-3 mt-4 rounded-5" style="background-color: rgba(255,229,180,0.57); height: 700px;">

            <h4 class="mt-3 ms-3">Filter By:</h4>
            <form method="GET" action="" class="ms-3 mt-3">
                <label for="phoneTypeFilter" class="fs-5">Phone Type:</label><br>
                <input class="me-2" type="checkbox" name="phone_type" value="Iphone 14 Pro Max" {% if 'Iphone 14 Pro Max' in selected_phone_type %}checked{% endif %}>Iphone 14 Pro Max<br>
                <input class="me-2" type="checkbox" name="phone_type" value="Iphone 14" {% if 'Iphone 14' in selected_phone_type %}checked{% endif %}>Iphone 14<br>
                <input class="me-2" type="checkbox" name="phone_type" value="Iphone 11" {% if 'Iphone 11' in selected_phone_type %}checked{% endif %}>Iphone 11<br>
                <input class="me-2" type="checkbox" name="phone_type" value="Sumsung S23" {% if 'Sumsung S23' in selected_phone_type %}checked{% endif %}>Sumsung S23<br>
                <input class="me-2" type="checkbox" name="phone_type" value="Sumsung A21" {% if 'Sumsung A21' in selected_phone_type %}checked{% endif %}>Sumsung A21<br>
                <input class="me-2" type="checkbox" name="phone_type" value="Huawei P30 Lite" {% if 'Huawei P30 Lite' in selected_phone_type %}checked{% endif %}>Huawei P30 Lite<br>

                <label for="materialFilter" class="fs-5">Material:</label><br>
                <input class="me-2" type="checkbox" name="material" value="Bamboo fiber" {% if 'Bamboo fiber' in selected_material %}checked{% endif %}>Bamboo fiber<br>
                <input class="me-2" type="checkbox" name="material" value="Recycled Plastic" {% if 'Recycled Plastic' in selected_material %}checked{% endif %}>Recycled Plastic<br>
                <input class="me-2" type="checkbox" name="material" value="Vegan Leather" {% if 'Vegan Leather' in selected_material %}checked{% endif %}>Vegan Leather<br>
                <input class="me-2" type="checkbox" name="material" value="Sillicone" {% if 'Sillicone' in selected_material %}checked{% endif %}>Sillicone<br>

                <label for="colorFilter" class="fs-5">Color:</label><br>
                <input class="me-2" type="checkbox" name="color" value="White" {% if 'White' in selected_color %}checked{% endif %}>White<br>
                <input class="me-2" type="checkbox" name="color" value="Blue" {% if 'Blue' in selected_color %}checked{% endif %}>Blue<br>
                <input class="me-2" type="checkbox" name="color" value="Green" {% if 'Green' in selected_color %}checked{% endif %}>Green<br>
                <input class="me-2" type="checkbox" name="color" value="Pink" {% if 'Pink' in selected_color %}checked{% endif %}>Pink<br>
                <input class="me-2" type="checkbox" name="color" value="Black" {% if 'Black' in selected_color %}checked{% endif %}>Black<br>
                <input class="me-2" type="checkbox" name="color" value="Red" {% if 'Red' in selected_color %}checked{% endif %}>Red<br>
                <input class="me-2" type="checkbox" name="color" value="Animal Print" {% if 'Animal Print' in selected_color %}checked{% endif %}>Animal Print<br>

                <button type="submit" class="btn btn-success mt-4 mb-2">Filter</button>
                <a href="{% url 'cases' %}" class="d-flex">Clear filters</a>
            </form>
        </div>

        <div class="col">
            <div class="row">
                {% for case in cases %}
                    <div class="mt-5 col-6 col-lg-3 text-center">
                    <a href="{% url 'case_details' case.id %}">
                        <img src="{{ MEDIA_URL }}{{ case.image.url }}" class="" style="height: 300px; width: 150px; ">
                    </a>
                    <p class="mt-1  fw-bold">{{ case.price }} $</p>
                    {% if user.is_authenticated and user.is_superuser %}
                        <a href="{% url 'delete_item' case.id %}" class="btn btn-danger">Delete</a>
                        <a href="{% url 'edit_item' case.id %}" class="btn btn-primary">Edit</a>
                    {% endif %}
                    </div>
                {% empty %}
                    <p>No cases found for "{{ query }}"</p>
                {% endfor %}
                </div>
        </div>
    </div>
</div>
</body>
</html>

CaseStoreApp/templates/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>SupCase</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
    <style>
        button:hover{
            color: white!important;
        }
         body {
            background-color: #f1f1f1;
        }
    </style>
</head>
<body>
<div class="container justify-content-center mt-5">
{% include 'header.html' %}<hr>
    <h3 class="mt-5 mb-3">Please leave us information for delivery</h3>
    <form method="POST" action="{% url 'checkout' %}">
      {% csrf_token %}
        {{ form.errors }}
      <div class="mb-3">
        {{ form.counrty.label_tag }}
        {{ form.counrty }}
      </div>

      <div class="mb-3">
        {{ form.city_postal.label_tag }}
        {{ form.city_postal }}
      </div>

      <div class="mb-3">
        {{ form.shipping_address.label_tag }}
        {{ form.shipping_address }}
      </div>

      <div class="mb-3">
        {{ form.phone_number.label_tag }}
        {{ form.phone_number }}
      </div>
      <div class="mb-3">
        {{ form.pay_with_card }}
        {{ form.pay_with_card.label_tag }}
        <p>You can unselect this to <strong>pay on delivery!</strong></p>
      </div>

        <div class="mb-3 ">
            <span>Card number: </span><input type="text" class="mt-4" id="card_number" ><br>
            <span>Expiration date: </span><input type="text" class="mt-4" id="ex_date"><br>
            <span>CVV: </span><input type="text" class="mt-4" id="cvv"><br>
      </div>
      <button type="submit" class="btn rounded-pill px-3 py-1 fw-bold fs-5"  style="background-color: indianred">Place Order</button>
    </form>

</div>

</body>

<script>
  var payWithCardInput = document.querySelector('#id_pay_with_card');
  var cardNumberInput = document.querySelector('#card_number');
  var expirationDateInput = document.querySelector('#ex_date');
  var cvvInput = document.querySelector('#cvv');

  // Function to toggle the required attribute
  function toggleRequiredAttribute() {
    if (payWithCardInput.checked) {
      cardNumberInput.required = true;
      expirationDateInput.required = true;
      cvvInput.required = true;
    } else {
      cardNumberInput.required = false;
      expirationDateInput.required = false;
      cvvInput.required = false;
    }
  }

  // Add event listener to toggle required attribute on change
  payWithCardInput.addEventListener('change', toggleRequiredAttribute);
  // Initial check on page load
  toggleRequiredAttribute();
</script>

</html>

CaseStoreApp/templates/edit_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>SupCase</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
    <style>
         body {
            background-color: #f1f1f1;
        }
    </style>
</head>
<body class="container">
{% include 'header.html' %}<hr>
{% block content %}
    <div class="mt-4">
          <h2>Edit Item</h2>
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary mb-5">Update Item</button>
          </form>
    </div>
{% endblock %}
</body>
</html>

CaseStoreApp/templates/final_site.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SupCase</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <style>
    body {
      background-color: #f5f5f5;
      padding: 20px;
    }

    .container {
      max-width: 550px;
      margin: 0 auto;
      text-align: center;
      background-color: #fff;
      border-radius: 5px;
      padding: 20px;
    }
    a:hover{
        color: white;
    }
  </style>
</head>
<body>

<div class="container mt-5">
    <h1 class="fs-1">Congratulations!</h1>
    <p class="fs-4">You have successfully made your order. You will receive your order in 7 days.</p>
    <a href="{% url 'cases' %}">
        <button class="btn rounded-pill px-3 py-1 fw-bold fs-5" style="background-color: indianred">Back to home page</button>
    </a>
</div>
</body>
</html>

CaseStoreApp/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SupCase</title>
    <link rel="icon" type="image/x-icon" href="https://freepngimg.com/download/phone_case/33082-2-phone-case-photos.png">
</head>
<body>
    <div class="row mt-5">
         <a href="{% url 'cases' %}" class="col-3 fw-bold text-decoration-none" style="color: #444F5A">
             <h1 class="mb-0">SupCase</h1>
         </a>
        <div class="col-9 text-end">
            {% if user.is_authenticated and user.is_superuser %}
                <a href="{% url 'add_item' %}" class="btn btn-primary me-3">Add New Item</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a href="{% url 'cart_items' %}" class="text-decoration-none">
                    <h4 style="color: #444F5A" class="d-inline me-3">MyCart</h4>
                </a>
                <a href="{% url 'logout' %}" class="text-decoration-none">
                    <h4 style="color: #444F5A" class="d-inline">LogOut</h4>
                </a>
            {% else %}
                <a href="{% url 'login' %}" class="text-decoration-none">
                        <h4 style="color: #444F5A" class="d-inline">LogIn</h4>
                </a>
            {% endif %}
        </div>
    </div>
</body>
</html>